import React from 'react';
import Link from 'next/link';
import { Metadata } from 'next';
import { Diamond, FileText } from 'lucide-react';

export const metadata: Metadata = {
  title: 'Terms of Service — Invex AI',
  description: 'Terms of Service for Invex AI — the AI-powered financial information platform.',
};

const SECTIONS = [
  {
    title: '1. Acceptance of Terms',
    body: `By accessing or using Invex AI ("Service"), you agree to be bound by these Terms of Service ("Terms"). If you do not agree to these Terms, do not use the Service. These Terms apply to all users, visitors, and others who access or use the Service.`,
  },
  {
    title: '2. Description of Service',
    body: `Invex AI is an artificial intelligence–powered financial information and education platform. The Service provides AI-generated portfolio suggestions, market analysis, stock information, and financial reports for educational and informational purposes only. Invex AI does not provide investment advice, brokerage services, financial planning, or any regulated financial services.`,
  },
  {
    title: '3. Not Financial Advice',
    body: `IMPORTANT: All content on Invex AI — including but not limited to portfolio recommendations, stock picks, buy/sell signals, allocation suggestions, and market analyses — is generated by AI models and is for EDUCATIONAL PURPOSES ONLY. It does NOT constitute:
    
• Investment advice or recommendations
• Research analysis under SEBI regulations  
• Solicitation or inducement to buy or sell securities
• Guaranteed future performance projections
• Legal, tax, or accounting advice

Invex AI is NOT registered with the Securities and Exchange Board of India (SEBI) as an Investment Adviser or Research Analyst. Always consult a SEBI-registered financial advisor before making investment decisions.`,
  },
  {
    title: '4. User Accounts',
    body: `When you create an account, you agree to provide accurate and complete information. You are responsible for maintaining the confidentiality of your account credentials and for all activities under your account. You agree to notify us immediately of any unauthorized use of your account. We reserve the right to terminate accounts that violate these Terms.`,
  },
  {
    title: '5. Acceptable Use',
    body: `You agree NOT to:
    
• Use the Service for any unlawful purpose
• Attempt to reverse-engineer, scrape, or extract data from the platform at scale
• Use AI-generated reports for professional financial advice without independent verification
• Misrepresent AI-generated content as professionally researched investment advice
• Share your account with third parties
• Attempt to circumvent rate limits or access controls`,
  },
  {
    title: '6. Intellectual Property',
    body: `The Service, including its original content, features, and functionality, is owned by Invex AI and is protected by applicable intellectual property laws. AI-generated reports produced during your session are provided to you for personal use only and may not be redistributed commercially.`,
  },
  {
    title: '7. Limitation of Liability',
    body: `TO THE MAXIMUM EXTENT PERMITTED BY LAW, INVEX AI SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING LOSS OF PROFITS OR INVESTMENT LOSSES, ARISING FROM:

• Your use of or inability to use the Service
• Reliance on AI-generated content for investment decisions
• Errors, inaccuracies, or omissions in financial data
• Unauthorized access to your data

Total liability of Invex AI shall not exceed the amount paid by you for the Service in the twelve months preceding the claim.`,
  },
  {
    title: '8. Disclaimer of Warranties',
    body: `THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND. INVEX AI DOES NOT WARRANT THAT:

• AI-generated recommendations will be profitable
• Market data will be accurate, complete, or timely
• The Service will be uninterrupted or error-free
• Results obtained will meet your expectations`,
  },
  {
    title: '9. Changes to Terms',
    body: `We reserve the right to modify these Terms at any time. We will provide notice of significant changes via email or through the Service. Your continued use of the Service after changes constitutes acceptance of the new Terms. It is your responsibility to review these Terms periodically.`,
  },
  {
    title: '10. Governing Law',
    body: `These Terms are governed by the laws of India. Any disputes shall be subject to the exclusive jurisdiction of courts in Mumbai, Maharashtra, India, subject to applicable consumer protection laws.`,
  },
  {
    title: '11. Contact',
    body: `For questions about these Terms, contact us at: legal@invex.ai`,
  },
];

export default function TermsPage() {
  return (
    <main style={{ background: '#0A0A0A', minHeight: '100vh', paddingBottom: '120px' }}>
      {/* Header */}
      <div style={{ borderBottom: '1px solid rgba(255,255,255,0.06)', padding: '20px 0' }}>
        <div style={{ maxWidth: '1280px', margin: '0 auto', padding: '0 48px', display: 'flex', alignItems: 'center', gap: '12px' }}>
          <Link href="/" style={{ display: 'flex', alignItems: 'center', gap: '8px', textDecoration: 'none' }}>
            <div style={{ width: '26px', height: '26px', background: '#C8F135', borderRadius: '7px', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
              <Diamond size={13} color="black" fill="black" />
            </div>
            <span style={{ color: '#fff', fontWeight: 700, fontSize: '14px' }}>Invex <span style={{ color: '#C8F135' }}>AI</span></span>
          </Link>
          <span style={{ color: 'rgba(255,255,255,0.2)', fontSize: '14px' }}>/</span>
          <span style={{ color: 'rgba(255,255,255,0.4)', fontSize: '14px' }}>Terms of Service</span>
        </div>
      </div>

      <div style={{ maxWidth: '860px', margin: '0 auto', padding: '64px 48px 0' }}>
        {/* Title */}
        <div style={{ marginBottom: '48px' }}>
          <div style={{ display: 'inline-flex', alignItems: 'center', gap: '8px', background: 'rgba(200,241,53,0.08)', border: '1px solid rgba(200,241,53,0.2)', borderRadius: '999px', padding: '6px 14px', marginBottom: '20px' }}>
            <FileText size={13} color="#C8F135" />
            <span style={{ color: '#C8F135', fontSize: '12px', fontWeight: 600, letterSpacing: '0.05em', textTransform: 'uppercase' }}>Legal</span>
          </div>
          <h1 style={{ fontSize: '42px', fontWeight: 700, color: '#fff', margin: '0 0 12px', lineHeight: 1.1 }}>
            Terms of Service
          </h1>
          <p style={{ color: 'rgba(255,255,255,0.45)', fontSize: '15px', margin: 0 }}>
            Effective date: March 1, 2026 · Last updated: March 2026
          </p>
        </div>

        {/* Highlighted notice */}
        <div style={{ background: 'rgba(200,241,53,0.05)', border: '1px solid rgba(200,241,53,0.2)', borderRadius: '14px', padding: '20px 24px', marginBottom: '40px' }}>
          <p style={{ color: 'rgba(255,255,255,0.7)', fontSize: '14px', margin: 0, lineHeight: 1.65 }}>
            <span style={{ color: '#C8F135', fontWeight: 700 }}>Summary: </span>
            Invex AI provides AI-generated financial information for educational purposes only. We are not SEBI registered, we don&apos;t manage money, and you should always verify our AI outputs with a real financial advisor before investing. By using our platform, you accept these terms.
          </p>
        </div>

        {/* Sections */}
        {SECTIONS.map((section, i) => (
          <section key={i} style={{ marginBottom: '32px' }}>
            <h2 style={{ color: '#fff', fontSize: '18px', fontWeight: 700, margin: '0 0 14px' }}>{section.title}</h2>
            <div style={{ background: 'rgba(255,255,255,0.02)', border: '1px solid rgba(255,255,255,0.07)', borderRadius: '12px', padding: '20px 24px' }}>
              <p style={{ color: 'rgba(255,255,255,0.6)', fontSize: '14px', lineHeight: 1.8, margin: 0, whiteSpace: 'pre-line' }}>
                {section.body}
              </p>
            </div>
          </section>
        ))}

        {/* Footer links */}
        <div style={{ display: 'flex', gap: '16px', paddingTop: '16px', borderTop: '1px solid rgba(255,255,255,0.08)' }}>
          <Link href="/legal/disclaimers" style={{ color: '#C8F135', fontSize: '13px', textDecoration: 'none' }}>View Disclaimers →</Link>
          <Link href="/legal/privacy" style={{ color: 'rgba(255,255,255,0.4)', fontSize: '13px', textDecoration: 'none' }}>Privacy Policy →</Link>
          <Link href="/" style={{ color: 'rgba(255,255,255,0.4)', fontSize: '13px', textDecoration: 'none' }}>← Back to Home</Link>
        </div>
      </div>
    </main>
  );
}
